version: 0.2

env:
  variables:
    TF_VERSION: "1.1.7"
    SRC_DIR: "infra/repo_with_lb"
    TF_ENV: "main"
    AWS_DEFAULT_REGION: "eu-central-1"
    AWS_ACCOUNT_ID: "836906079004"
    IMAGE_REPO_NAME: "wb-repository"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Install Terraform...
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"

      - echo Terraform installed.
      
      - echo Terraform init...
      
      - cd "$CODEBUILD_SRC_DIR"
      - cd "$SRC_DIR"
      - terraform init -input=false --backend-config=../env_vars/${TF_ENV}.conf
      - terraform ${TF_ACTION} -input=false -var-file=../env_vars/${TF_ENV}.tfvars -auto-approve
      - echo "Terraform init completed on `date`"

      - echo Install or check docker...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 & timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Docker ready.

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG ./containers/demo/Demo.Cs.Api
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG          

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      

artifacts:
  files:
    - '**/*'
